const Discord = require("discord.js");
const filterLevels = ['Off', 'No Role', 'Everyone'];
const verificationLevels = ['None', 'Low', 'Medium', '(╯°□°）╯︵ ┻━┻', '┻━┻ ﾐヽ(ಠ益ಠ)ノ彡┻━┻'];

exports.run = async function(client, message, args) {
 {

      const embed = new Discord.MessageEmbed()
      .setAuthor(`${message.guild.name} - Server Information`, message.guild.iconURL)
      .setColor(0x00AE86)
      .setThumbnail(message.guild.iconURL)
      .addField('❯ Name', message.guild.name, true)
      .addField('❯ ID', message.guild.id, true)
      .addField('❯ Region', message.guild.region.toUpperCase(), true)
      .addField('❯ Creation Date', message.guild.createdAt.toDateString(), true)
  //    .addField('❯ Explicit Filter', filterLevels[message.guild.explicitContentFilter], true)
    //  .addField('❯ Verification Level', verificationLevels[message.guild.verificationLevel], true)
      .addField('❯ Owner', message.guild.owner.user.tag, true)
      .addField('❯ Members', message.guild.memberCount, true)
      .addField('❯ Roles', message.guild.roles.cache.size, true)
      .addField('❯ Channels', message.guild.channels.cache.size, true)
      .setFooter(`Generated by ${message.author.username}#${message.author.discriminator}`, message.author.avatarURL)
      .setTimestamp()
      message.channel.send({embed});
}


};

exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [],
  permLevel: "User"
};

exports.help = {
  name: 'serverinfo',
  category: "Miscellaneous",
  description: 'Shows information about the server',
  usage: 'serverinfo'
};
